name: Release APK

on:
  push:
    branches:
      - main
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Flutter Deployment
        uses: jeanluc243/Flutter-Deployment@0.1
