name: Release APK

on:
  push:
    branches:
      - main
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.0'  # Specify the Flutter version here

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Flutter Deployment
        uses: jeanluc243/Flutter-Deployment@0.1
        with:
          # If the action requires inputs, provide them here. 
          # For example:
          # api_key: ${{ secrets.YOUR_SECRET }}
